# Generated by Django 5.0.7 on 2025-01-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_job_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profilephotos/'),
        ),
    ]
