# Generated by Django 5.0.7 on 2025-05-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0012_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='lastname',
        ),
    ]
