# Generated by Django 5.0.7 on 2025-05-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0013_rename_firstname_userdetail_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='mobile',
            field=models.CharField(default='9876543211', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='notice_period',
            field=models.CharField(default='15', max_length=10),
            preserve_default=False,
        ),
    ]
